name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/71chjzkc/gki-clo.git
          kernel-branch: 6.6.56
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 15
          aosp-clang-version: r510928
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
