name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: StockKernel
    runs-on: ubuntu-22.04
    steps:
      - name: StockKernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git
          kernel-branch: onyx-v-oss
          config: onyx_perf.config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 15
          aosp-clang-version: r383902
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
